### ISSUE TITLE
Fine tuned model - Download link not working 

### ISSUE THREAD

**Issue by ankitasingh001** [AI4Bharat/IndicWav2Vec#1]
On clicking the download link , it shows "shows : This XML file does not appear to have any style information associated with it. The document tree is shown below."
Link for reference : https://storage.googleapis.com/indicwav2vec-public/fine-tuning-ckpts/hindi_large.pt
Please do recheck the links on the webpage or provide alternate links.
Thanks!

**Comment by gowtham1997** [comment]
This is fixed and should be working now.

**Comment by ajayrao80** [comment]
> This is fixed and should be working now.

It is not working. I'm facing the same problem.
