### ISSUE TITLE
Please guide on how to create the subset of 70 hrs for training on openslr data.

### ISSUE THREAD

**Issue by raotnameh** [AI4Bharat/IndicWav2Vec#12]
In the paper openslr specific subset is talked about for training. But there is no mention of how to create the 70 hr subset in the reference paper by "Vishwas M. Shetty, S. Umesh".

Please guide on how to create the subset of 70 hrs for training on openslr data.

**Comment by tahirjmakhdoomi** [comment]
It'll be more appropriate if you email the authors of this paper. I am sure they can share the meta information with you directly.
