### ISSUE TITLE
Model download link not working

### ISSUE THREAD

**Issue by Mayankd2019** [AI4Bharat/IndicWav2Vec#19]
The link to download the models on your documentation page isn't working. When I click on the link to download the file the following error is displayed : 
<Error>
    <Code>UserProjectAccountProblem</Code>
    <Message>The project to be billed is associated with a delinquent billing account.</Message>
    <Details>The billing account for the owning project is disabled in state delinquent</Details>
</Error>

**Comment by sumanthd17** [comment]
We are looking into this, will get back ASAP

**Comment by ajayrao80** [comment]
I'm facing the same problem. Not just for models but also for datasets.

**Comment by tahirjmakhdoomi** [comment]
Can you please try again?
