### ISSUE TITLE
Kannada language finetuned model

### ISSUE THREAD

**Issue by manualsh** [AI4Bharat/IndicWav2Vec#24]
Hello Team AI4Bharat,

Could you please look into including the kannada language finetuned model. Couldn't find the kannada model in the section on finetuned models here
Reference:
https://github.com/AI4Bharat/IndicWav2Vec#download-models

Thank you,
Manu

**Comment by tahirjmakhdoomi** [comment]
Hi [manualsh]
We have the Kannada model trained, and we will be open-sourcing it very soon.

**Comment by manualsh** [comment]
Thank you @tahirjmakhdoomi 

Could you please link to the model in Readme table.

It's still  missing in the above table. 
https://github.com/AI4Bharat/IndicWav2Vec#download-models

Could you please  look into this?

**Comment by adimyth** [comment]
@tahirjmakhdoomi It's been 1.5 years since your last comment about making the Kannada model open source & it is yet to be released. Can you kindly revert?
