### ISSUE TITLE
uable to FINETUNE from a PRETRAINED model

### ISSUE THREAD

**Issue by mujhenahiata** [AI4Bharat/IndicWav2Vec#27]
NEED HELP/FIX ASAP
already logged issues.
https://github.com/facebookresearch/fairseq/issues/3683 : https://github.com/facebookresearch/fairseq/issues/3683

AssertionError: Could not infer task type from {'_name': 'temp_sampled_audio_pretraining', 'data': '/home/sibadatta/asr/AI4BHARAT/IndicWav2Vec/data/hindi/manifest', 'max_sample_size': 320000, 'min_sample_size': 32000, 'normalize': True, 'sampling_alpha': 0.7}. Available argparse tasks: dict_keys(['hubert_pretraining', 'audio_pretraining', 'audio_finetuning', 'sentence_ranking', 'translation_multi_simple_epoch', 'cross_lingual_lm', 'speech_unit_modeling', 'translation', 'multilingual_translation', 'speech_to_text', 'text_to_speech', 'frm_text_to_speech', 'translation_lev', 'translation_from_pretrained_xlm', 'sentence_prediction', 'simul_speech_to_text', 'simul_text_to_text', 'online_backtranslation', 'multilingual_masked_lm', 'language_modeling', 'legacy_masked_lm', 'multilingual_language_modeling', 'sentence_prediction_adapters', 'semisupervised_translation', 'denoising', 'masked_lm', 'translation_from_pretrained_bart', 'multilingual_denoising', 'speech_to_speech', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt']). Available hydra tasks: dict_keys(['hubert_pretraining', 'audio_pretraining', 'audio_finetuning', 'speech_unit_modeling', 'translation', 'translation_lev', 'translation_from_pretrained_xlm', 'sentence_prediction', 'simul_text_to_text', 'language_modeling', 'multilingual_language_modeling', 'sentence_prediction_adapters', 'masked_lm', 'dummy_lm', 'dummy_masked_lm'])

What have you tried?
I created the manifest as prescribed and used used this line

fairseq-hydra-train
task.data=/path/to/finetune/manifest/directory/for/a/particular/language
common.wandb_project=
model.w2v_path=/path/to/pretrained/model_large.pt
common.log_interval=50
common.log_format=tqdm
dataset.max_tokens=1000000
checkpoint.save_dir=/path/to/save/model/fine_tune_checkpoints
+optimization.update_freq='[1]'
--config-dir /path/to/configs/directory
--config-name ai4b_xlsr"

What's your environment?
and just to test the code, i wanted to run it on CPU

**Comment by tahirjmakhdoomi** [comment]
Hi [mujhenahiata]
Can you run the following set of commands?

m = torch.load(<the pretrained model checkpoint>)
m['cfg']['task']['_name'] = 'audio_finetuning'
torch.save(m,"new_checkpoint.pt")

Then you can use the "new_checkpoint.pt" for all your finetunings.

**Comment by ussenuk** [comment]
I'm experiencing the same problem when finetuning IndicWav2Vec, the above solution was not quite explicit
