### ISSUE TITLE
Are API endpoints working?

### ISSUE THREAD

**Issue by TejaswiniiB** [AI4Bharat/IndicWav2Vec#28]
Hi, 
I am trying to run once using the provided api endpoints. But I am getting error as shown below. How to solve it?

```
{'_content': b'upstream connect error or disconnect/reset before headers. reset reason: remote reset', '_content_consumed': True, '_next': None, 'status_code': 503, 'headers': {'Server': 'nginx/1.23.1', 'Date': 'Mon, 26 Sep 2022 09:21:56 GMT', 
'Content-Type': 'text/plain', 'Content-Length': '85', 'Connection': 'keep-alive', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'}, 'raw': <urllib3.response.HTTPResponse object at 0x7f458c896150>, 
'url': 'https://ai4b-dev-asr.ulcacontrib.org/asr/v1/recognize/hi?config=language&config=transcriptionFormat&config=audioFormat&audio=audioUri', 
'encoding': 'ISO-8859-1', 'history': [], 'reason': 'Service Unavailable', 'cookies': <RequestsCookieJar[]>, 'elapsed': 
datetime.timedelta(microseconds=902142), 'request': <PreparedRequest [GET]>, 'connection': 
<requests.adapters.HTTPAdapter object at 0x7f458c838290>}
```

![image](https://user-images.githubusercontent.com/24452276/192242437-3c46e6d5-4c88-4dd5-bfa1-e2ec99e9cbb0.png)

**Comment by tahirjmakhdoomi** [comment]
It seems you are making a get request, However, a POST request is required.

**Comment by mln-wave** [comment]
Hi @tahirjmakhdoomi 
I updated as post request , but Im getting error as "Audio input not specified". But I have given audio uri as mentioned in [here](https://github.com/AI4Bharat/IndicWav2Vec#hosted-api-usage) . Can you tell what to change to resolve it?
![image](https://user-images.githubusercontent.com/110157037/192429507-79bd8612-9787-4767-a278-4c4a759306ff.png)
