### ISSUE TITLE
Audio input not specified

### ISSUE THREAD

**Issue by mln-wave** [AI4Bharat/IndicWav2Vec#29]
Hi @tahirjmakhdoomi

Since [this discussion](https://github.com/AI4Bharat/IndicWav2Vec/issues/28#issuecomment-1258942697) is closed and I'm not able to re-open, asking it here: 

I updated it as post request , but Im getting error as "Audio input not specified". But I have given audio uri as mentioned in [here](https://github.com/AI4Bharat/IndicWav2Vec#hosted-api-usage) . Can you tell what to do to resolve it?

![image](https://user-images.githubusercontent.com/110157037/192430245-f2975fbe-be2d-4f12-ae2b-049125622424.png)

**Comment by tahirjmakhdoomi** [comment]
Hi @mln-wave 
Can you please try accessing the model directly from [here](https://bhashini.gov.in/ulca/search-model/63074ab02f73e063a4a83270/model)

In addition, if you want a running server, we have put a ULCA_Compliance code, you can use that alongside our models to create a deployable ASR inference system.

**Comment by mln-wave** [comment]
Ok, I got what you said @tahirjmakhdoomi 

Actually I tried running the code by downloading the models. But I was getting installation issues. Mainly with flashlight, though it was successfully installed, it is giving import error. Not able to find the reason !!
Do you know what can be done to overcome it?

![image](https://user-images.githubusercontent.com/110157037/192537191-08a7cbca-72a7-4a35-b0e3-9ab80a830213.png)

![image](https://user-images.githubusercontent.com/110157037/192537416-bb2c087d-c801-4f6c-a7bb-6c49407609b9.png)

**Comment by tahirjmakhdoomi** [comment]
Okay Interesting, The problem is that flashlight has made some modification in their codebase. Could you please use the "0.3" branch of flashlight and see if that resolves the issues.
 
 You could simply do "git checkout 0.3" after git cloning

**Comment by mln-wave** [comment]
Ok, thankyou @tahirjmakhdoomi 
Tried as you said, but still shows as successful installation, but not able to import properly. 
I am able to just import flashlight as `import flashlight`, but not anything under it !! ? Can see in below pics.
![image](https://user-images.githubusercontent.com/110157037/192552113-88714da4-7d9b-4038-ba85-6e82d1e27e83.png)
![image](https://user-images.githubusercontent.com/110157037/192552420-747d7117-1412-4cd3-a6f6-791d4d7eec74.png)

**Comment by tahirjmakhdoomi** [comment]
Can you try 0.2 branch?

**Comment by mln-wave** [comment]
Hi @tahirjmakhdoomi 
Actually flashlight is installing properly from `main` branch, and getting issues when installing from other branches (`0.2` or `0.3`) using the commands you mentioned. 

1. When installed from `main` branch:
It got installed properly without errors. I checked the path where it mentioned as installed.
From the below image, we can see all the `text`, `audio` etc directories in `lib` directory. So, seems like all installation libraries are present as expected, but there is some small simple mistake because of which Im not able to import I think. 
![image](https://user-images.githubusercontent.com/110157037/192951662-6f84ea07-4567-49e5-9069-8c4622bf1af5.png)


2. When installed from `0.3` branch, got the below error, and didn't get installed. 

```
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "setup.py", line 133, in <module>
    python_requires=">=3.6",
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 105, in build_extensions
    ["cmake", source_dir] + cmake_args, cwd=self.build_temp, env=env
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/content/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/content/flashlight/bindings/python/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_ALL_LIBS=ON', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CUDA', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
/content

```

**Comment by tahirjmakhdoomi** [comment]
Can you try this commit?

git checkout 06ddb51857ab1780d793c52948a0759f0ccc6ddb

**Comment by mln-wave** [comment]
Hi @tahirjmakhdoomi 

Thank you for your support!
I tried the commit you've mentioned, but getting the same above error during installation of flashlight.

![image](https://user-images.githubusercontent.com/110157037/194464288-77440aac-7fd8-4127-9289-b1b50d482f24.png)

![image](https://user-images.githubusercontent.com/110157037/194464344-bd6b2baa-ae8c-4812-bb35-bdc8ae08e575.png)

**Comment by tahirjmakhdoomi** [comment]
Can you send me a meeting invite this weekend. We can sit and see what's wrong.

**Comment by arjunbahuguna** [comment]
Hi! I'm facing a similar issue when installing flashlight. I've followed the steps you mentioned @tahirjmakhdoomi but the installation is failing. What was the fix?

**Comment by tahirjmakhdoomi** [comment]
Could you please share me a snapshot of error that you are encountering?
