### ISSUE TITLE
Where can someone find the exact download link for NoA? 

### ISSUE THREAD

**Issue by raotnameh** [AI4Bharat/IndicWav2Vec#3]
Download the NoA from the publicly available links. 

Please elaborate on this step a little more.

**Comment by gowtham1997** [comment]
We missed adding the link in the documentation. You can crawl the datasets from this [link](https://newsonair.gov.in/RNU-NSD-Audio-Archive-Search.aspx).

I don't think we have the required permissions to distribute this. We will update the GitHub page if we opensource this crawled dataset in the future

![image](https://user-images.githubusercontent.com/9641196/151504188-cb9208b1-60fd-48d9-9857-ca41f556d062.png)

**Comment by raotnameh** [comment]
@gowtham1997 Thank you.
