### ISSUE TITLE
Configuration of models at hosted inference.

### ISSUE THREAD

**Issue by BakingBrains** [AI4Bharat/IndicWav2Vec#36]
Hello @tahirjmakhdoomi 

Thanks for the great work.

I can see the out of the model from API call and the output from local inference has a huge difference. Can you please suggest the configuration to inference locally.

Thanks and Regards.

**Comment by tahirjmakhdoomi** [comment]
Hi @BakingBrains 
We have updated the models.
Please visit **https://github.com/AI4Bharat/vistaar**

**Comment by BakingBrains** [comment]
Thank you @tahirjmakhdoomi.
I will check.
