### ISSUE TITLE
Updation of missing link to Kannada and Malayalam language finetuned models in Readme

### ISSUE THREAD

**Issue by manualsh** [AI4Bharat/IndicWav2Vec#40]
Could you please link to the Kannada and Malayalam language finetuned models in the Readme table. It's still missing in the above table. https://github.com/AI4Bharat/IndicWav2Vec#download-models 
Could you please look into this? 

![Edit Screenshot (1152)](https://github.com/AI4Bharat/IndicWav2Vec/assets/28729739/6d66a84a-2df9-4537-b9a6-1661783b8bab)

**Comment by tahirjmakhdoomi** [comment]
I have added the links for Kannada and Malayalam models. 
Closing this issue.
