### ISSUE TITLE
Not able to load any checkpoint

### ISSUE THREAD

**Issue by harveenchadha** [AI4Bharat/IndicWav2Vec#5]
Hello,

I tried to load the hindi large checkpoint but none of the checkpoints are loading. Which version of fairseq was used for training?

I am getting the following error:

<img width="1223" alt="Screenshot 2022-01-26 at 12 33 42 AM" src="https://user-images.githubusercontent.com/30959215/151042088-f5c88a6e-e0ec-4d49-97f9-af1459339cb2.png">

**Comment by gowtham1997** [comment]
From the error, it looks like "sampling_alpha" is not defined. 
This is a variable we defined [here](https://github.com/AI4Bharat/IndicWav2Vec/blob/7deeeb565b13eda1dee3b9aa919d763557e1443c/custom_task/temp_based_audio_pretraining.py#L110) for temperature based sampling. 

Can you tell us how you are trying to load the checkpoint? Im guessing that you are missing to add `common.user_dir=custom_task` ( you need to pass custom_task folder where temp based sampling is implemented for fairseq to load this correctly)

**Comment by harveenchadha** [comment]
I am using sfi.py script from inference folder present [here](https://github.com/AI4Bharat/IndicWav2Vec/blob/main/w2v_inference/scripts/sfi.py)

**Comment by gowtham1997** [comment]
Looking at our fairseq, there was one change we made to solve a similar issue earlier. 

The change was to make `remove_missing=False` in this [line](https://github.com/pytorch/fairseq/blob/4a7835b79423b152938e90b88224dac499560d11/fairseq/dataclass/utils.py#L477). Can you try to check if the loading works after you add this?

**Comment by harveenchadha** [comment]
Thank you.

This worked!
