### ISSUE TITLE
Kenlm doesn't works with Batch Inference

### ISSUE THREAD

**Issue by harveenchadha** [AI4Bharat/IndicWav2Vec#6]
Hello,

I tried the single file inference, this worked with both viterbi and kenlm. Then I moved to batch inference, here viterbi works just fine but kenlm throws an exception:

<img width="1163" alt="Screenshot 2022-01-27 at 4 55 01 PM" src="https://user-images.githubusercontent.com/30959215/151350050-98f8befa-4f0e-4b0d-a7fd-14c29bc2d1ba.png">

Normally this exception comes when the vocab of the model and the language model is different but I think this would be taken care of for sure. Can you suggest something to run this? I am also surprised as I am not getting this error in single file inference but in batch mode.

Thanks!

**Comment by tahirjmakhdoomi** [comment]
I see. As a quick fix can you try commenting out the assert statement in w2l_decoder (inside __init__,W2lKenLMDecoder) and see if that works?

**Comment by harveenchadha** [comment]
Even in my wildest dreams, I would not have imagined that this would work but it did. Looks like assert is doing nothing 😃

Thank you.
