### ISSUE TITLE
Getting an undefined symbol error

### ISSUE THREAD

**Issue by raotnameh** [AI4Bharat/IndicWav2Vec#7]
Hi Team, 
Getting this error: 
```
ImportError: /opt/conda/lib/python3.8/site-packages/fused_layer_norm_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv
```

Full trace 

root@297b396be589:/workspace/hemant/IndicWav2Vec/w2v_inference/scripts# bash infer_auto.sh 0 "hindi_mucs" "large" "hi[26/1834]32 > out.txt                                                                                                                  vi 2022-01-28 05:32:34 | INFO | __main__ | | decoding with criterion ctc                                                      2022-01-28 05:32:34 | INFO | __main__ | | loading model(s) from /workspace/hemant/IndicWav2Vec/w2v_inference/checkpoints/acoustic_model/large/hindi_large.pt                                                                                                out     Traceback (most recent call last):                                                                                      File "../infer/infer.py", line 451, in <module>                                                                                 cli_main()                                                                                                                  File "../infer/infer.py", line 447, in cli_main                                                                                 main(args)                                                                                                                  File "../infer/infer.py", line 236, in main                                                                                     models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(                                                    File "/home/fairseq/fairseq/checkpoint_utils.py", line 469, in load_model_ensemble_and_task                                     model = task.build_model(cfg.model, from_checkpoint=True)                                                                   File "/home/fairseq/fairseq/tasks/audio_finetuning.py", line 193, in build_model                                                model = super().build_model(model_cfg, from_checkpoint)                                                                     File "/home/fairseq/fairseq/tasks/audio_pretraining.py", line 197, in build_model                                               model = super().build_model(model_cfg, from_checkpoint)                                                                     File "/home/fairseq/fairseq/tasks/fairseq_task.py", line 335, in build_model                                                    model = models.build_model(cfg, self, from_checkpoint)                                                                      File "/home/fairseq/fairseq/models/__init__.py", line 106, in build_model                                                       return model.build_model(cfg, task)                                                                                         File "/home/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 212, in build_model                                           w2v_encoder = Wav2VecEncoder(cfg, len(task.target_dictionary))                                                              File "/home/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 411, in __init__                                              model = task.build_model(w2v_args.model, from_checkpoint=True)                                                              File "/home/fairseq/fairseq/tasks/audio_pretraining.py", line 197, in build_model                                               model = super().build_model(model_cfg, from_checkpoint)                                                                     File "/home/fairseq/fairseq/tasks/fairseq_task.py", line 335, in build_model                                                    model = models.build_model(cfg, self, from_checkpoint)                                                                      File "/home/fairseq/fairseq/models/__init__.py", line 106, in build_model                                                       return model.build_model(cfg, task)                                                                                         File "/home/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 410, in build_model                                               return cls(cfg)                                                                                                             File "/home/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 390, in __init__                                                  self.encoder = encoder_cls(cfg)                                                                                             File "/home/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 992, in __init__                                                  [self.build_encoder_layer(args) for _ in range(args.encoder_layers)]                                                        File "/home/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 992, in <listcomp>                                                [self.build_encoder_layer(args) for _ in range(args.encoder_layers)]                                                        File "/home/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 920, in build_encoder_layer                                       layer = TransformerSentenceEncoderLayer(                                                                                    File "/home/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 1213, in __init__                                                 self.self_attn_layer_norm = LayerNorm(self.embedding_dim)      
File "/home/fairseq/fairseq/modules/layer_norm.py", line 32, in LayerNorm                                                       return FusedLayerNorm(normalized_shape, eps, elementwise_affine)                                                            File "/opt/conda/lib/python3.8/site-packages/apex/normalization/fused_layer_norm.py", line 133, in __init__                     fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")                                                    File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module                                               return _bootstrap._gcd_import(name[level:], package, level)                                                                 File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                               File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                             File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                    File "<frozen importlib._bootstrap>", line 657, in _load_unlocked                                                             File "<frozen importlib._bootstrap>", line 556, in module_from_spec                                                           File "<frozen importlib._bootstrap_external>", line 1166, in create_module                                                    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                ImportError: /opt/conda/lib/python3.8/site-packages/fused_layer_norm_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv

**Comment by gowtham1997** [comment]
Hey,
This could be due to some errors in nvidia apex installation. 
I found a similar issue [here](https://github.com/NVIDIA/apex/issues/370). Can you please check that out?

**Comment by raotnameh** [comment]
@gowtham1997 
In the Dockerfile, the commands to install apex are commented. 
Is it done on purpose?

**Comment by raotnameh** [comment]
@gowtham1997 If I am using docker, I should not have this error.
