### ISSUE TITLE
What is the difference between different language model names? 

### ISSUE THREAD

**Issue by raotnameh** [AI4Bharat/IndicWav2Vec#8]
Hi Team, 
@gowtham1997 
What is the difference?  small_2 and small or comb?

```
bash infer_auto.sh 0 "hindi_mucs" "large" "mucs_small_2" 2 -4 1024 &\
bash infer_auto.sh 0 "hindi_mucs" "large" "mucs_large_2" 2 -4 1024 &\
bash infer_auto.sh 0 "hindi_mucs" "large" "comb" 2 -4 1024 &\
bash infer_auto.sh 0 "hindi_mucs" "large" "mucs_small" 2 -4 1024 &\
bash infer_auto.sh 0 "hindi_mucs" "large" "mucs_large" 2 -4 1024 &\
```

**Comment by raotnameh** [comment]
@gowtham1997

**Comment by RamanHacks** [comment]
Hi @raotnameh , the language models differ in terms of the data/lexicon used for training them. For more info, please refer to Table 3 of our [paper](https://arxiv.org/pdf/2111.03945.pdf): 
small/small_2 corresponds to the M4 row 
large/large_2 corresponds to the M5 row
comb corresponds to the M6 row (augmented_lexicon)
