### ISSUE TITLE
Decoding is slow. Anything to make it fast? It is not using multiple cores. At least the default commands in the README.

### ISSUE THREAD

**Issue by raotnameh** [AI4Bharat/IndicWav2Vec#9]
I am using docker.

**Comment by RamanHacks** [comment]
Hi @raotnameh , decoding depends on the beam size, size of language model, etc. Also the current fairseq implementation doesn't provide for batch inference, hence the process is slow (and runs on single-thread)! 
We are currently working on to release a HF-compatible model. That should speed up the decoding (through batch inferencing).
